import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeWrapper } from "@/src/Components/Theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Designare",
  description: "Generated by youyuhsuan",
};

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <ThemeWrapper>{props.children}</ThemeWrapper>
      </body>
    </html>
  );
}
