import Nav from "@/src/Components/Nav";
import Slogan from "@/src/Components/Slogan";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Designare",
  description: "Generated by youyuhsuan",
};

export default function Home() {
  return (
    <>
      <Nav />
      <main>
        <Slogan />
      </main>
    </>
  );
}
