import type { Metadata } from "next";
import Nav from "@/src/Components/MainNav";
import HeroSection from "@/src/Components/HeroSection";
import WebsiteTemplateShowcase from "@/src/Components/Card";
import KeyFeaturesSection from "@/src/Components/KeyFeaturesSection";

export const metadata: Metadata = {
  title: "Designare",
  description: "Generated by youyuhsuan",
};

export default function Home() {
  return (
    <>
      <Nav />
      <main>
        <HeroSection />
        <WebsiteTemplateShowcase />
        <KeyFeaturesSection />
      </main>
    </>
  );
}
